import type { CollectionConfig } from 'payload'
import { ensureStableNodeId } from '../hooks/ensureStableNodeId'

/**
 * MindmapNodes Collection
 *
 * Stores individual nodes within mindmaps.
 * Based on the MindmapNode domain type from @mindmap/domain.
 *
 * ⚠️ CRITICAL: nodeId is STABLE and IMMUTABLE
 * - Auto-generated on creation
 * - NEVER changes after creation (enforced by hook)
 * - Used for references from Flashcards and Comments
 *
 * Features:
 * - Stable nodeId (enforced by ensureStableNodeId hook)
 * - Content (text and richText)
 * - Position (x, y coordinates)
 * - Metadata (timestamps, author)
 * - Relationship to parent Mindmap
 */
export const MindmapNodes: CollectionConfig = {
  slug: 'mindmap-nodes',
  admin: {
    useAsTitle: 'nodeId',
    defaultColumns: ['nodeId', 'mindmap', 'updatedAt'],
  },
  hooks: {
    beforeChange: [ensureStableNodeId],
  },
  access: {
    // TEMPORARY: Relaxed access control for debugging E2E tests
    // TODO: Restore strict access control after fixing the issue
    read: ({ req: { user } }) => {
      if (!user) return false
      // Allow all authenticated users to read all nodes (for debugging)
      return true
    },
    create: ({ req: { user } }) => Boolean(user),
    update: ({ req: { user } }) => {
      if (!user) return false
      // Allow all authenticated users to update all nodes (for debugging)
      return true
    },
    delete: ({ req: { user } }) => {
      if (!user) return false
      // Allow all authenticated users to delete all nodes (for debugging)
      return true
    },
  },
  fields: [
    {
      name: 'nodeId',
      type: 'text',
      required: false, // Not required in schema - auto-generated by hook
      unique: true,
      label: 'Node ID',
      admin: {
        readOnly: true,
        description: '⚠️ STABLE ID - Never changes after creation. Auto-generated by hook.',
      },
    },
    {
      name: 'mindmap',
      type: 'relationship',
      relationTo: 'mindmaps',
      required: true,
      hasMany: false,
      label: 'Parent Mindmap',
    },
    {
      name: 'content',
      type: 'group',
      label: 'Content',
      fields: [
        {
          name: 'text',
          type: 'textarea',
          label: 'Plain Text',
        },
        {
          name: 'richText',
          type: 'richText',
          label: 'Rich Text',
        },
      ],
    },
    {
      name: 'position',
      type: 'group',
      label: 'Position',
      fields: [
        {
          name: 'x',
          type: 'number',
          required: true,
          label: 'X Coordinate',
        },
        {
          name: 'y',
          type: 'number',
          required: true,
          label: 'Y Coordinate',
        },
      ],
    },
    {
      name: 'metadata',
      type: 'group',
      label: 'Metadata',
      fields: [
        {
          name: 'author',
          type: 'relationship',
          relationTo: 'users',
          label: 'Author',
          defaultValue: ({ user }) => user?.id,
        },
      ],
    },
  ],
  timestamps: true,
}

