import { test, expect } from '@playwright/test'

/**
 * E2E Tests for Mindmap Nodes
 *
 * Tests the creation and management of mindmap nodes via the API.
 * Focuses on the nodeId auto-generation and validation.
 */

const CMS_URL = process.env.NEXT_PUBLIC_CMS_URL || 'http://localhost:3001'

test.describe('Mindmap Nodes API', () => {
  let mindmapId: string

  test.beforeAll(async ({ request }) => {
    // Create a test mindmap first
    const response = await request.post(`${CMS_URL}/api/mindmaps`, {
      data: {
        title: 'E2E Test Mindmap for Nodes',
        description: 'Testing node creation',
        status: 'draft',
      },
    })

    expect(response.ok()).toBeTruthy()
    const data = await response.json()
    mindmapId = data.doc.id
  })

  test('should create node without providing nodeId (auto-generated)', async ({ request }) => {
    const response = await request.post(`${CMS_URL}/api/mindmap-nodes`, {
      data: {
        // nodeId NOT provided - should be auto-generated by hook
        mindmap: mindmapId,
        content: {
          text: 'Test Node 1',
        },
        position: {
          x: 100,
          y: 100,
        },
      },
    })

    expect(response.status()).toBe(201)
    const data = await response.json()
    
    expect(data.doc).toBeDefined()
    expect(data.doc.nodeId).toBeDefined()
    expect(typeof data.doc.nodeId).toBe('string')
    expect(data.doc.nodeId.length).toBeGreaterThan(0)
    expect(data.doc.content.text).toBe('Test Node 1')
    expect(data.doc.position.x).toBe(100)
    expect(data.doc.position.y).toBe(100)
  })

  test('should create node with provided nodeId', async ({ request }) => {
    const customNodeId = 'custom-node-id-123'
    
    const response = await request.post(`${CMS_URL}/api/mindmap-nodes`, {
      data: {
        nodeId: customNodeId,
        mindmap: mindmapId,
        content: {
          text: 'Test Node 2',
        },
        position: {
          x: 200,
          y: 200,
        },
      },
    })

    expect(response.status()).toBe(201)
    const data = await response.json()
    
    expect(data.doc.nodeId).toBe(customNodeId)
    expect(data.doc.content.text).toBe('Test Node 2')
  })

  test('should enforce nodeId immutability on update', async ({ request }) => {
    // Create a node
    const createResponse = await request.post(`${CMS_URL}/api/mindmap-nodes`, {
      data: {
        mindmap: mindmapId,
        content: { text: 'Node for Immutability Test' },
        position: { x: 300, y: 300 },
      },
    })

    expect(createResponse.status()).toBe(201)
    const createData = await createResponse.json()
    const originalNodeId = createData.doc.nodeId
    const nodeDocId = createData.doc.id

    // Try to update the nodeId (should fail or be ignored)
    const updateResponse = await request.patch(`${CMS_URL}/api/mindmap-nodes/${nodeDocId}`, {
      data: {
        nodeId: 'different-node-id',
        content: { text: 'Updated content' },
      },
    })

    // The update might succeed but nodeId should remain unchanged
    const updateData = await updateResponse.json()
    expect(updateData.doc.nodeId).toBe(originalNodeId)
    expect(updateData.doc.content.text).toBe('Updated content')
  })

  test('should require mindmap relationship', async ({ request }) => {
    const response = await request.post(`${CMS_URL}/api/mindmap-nodes`, {
      data: {
        // Missing mindmap relationship
        content: { text: 'Test Node' },
        position: { x: 0, y: 0 },
      },
    })

    expect(response.status()).toBe(400)
    const data = await response.json()
    expect(data.errors).toBeDefined()
  })

  test('should require position coordinates', async ({ request }) => {
    const response = await request.post(`${CMS_URL}/api/mindmap-nodes`, {
      data: {
        mindmap: mindmapId,
        content: { text: 'Test Node' },
        // Missing position
      },
    })

    expect(response.status()).toBe(400)
    const data = await response.json()
    expect(data.errors).toBeDefined()
  })

  test('should fetch nodes for a mindmap', async ({ request }) => {
    // Create a few nodes
    await request.post(`${CMS_URL}/api/mindmap-nodes`, {
      data: {
        mindmap: mindmapId,
        content: { text: 'Node A' },
        position: { x: 0, y: 0 },
      },
    })

    await request.post(`${CMS_URL}/api/mindmap-nodes`, {
      data: {
        mindmap: mindmapId,
        content: { text: 'Node B' },
        position: { x: 100, y: 100 },
      },
    })

    // Fetch all nodes for this mindmap
    const response = await request.get(
      `${CMS_URL}/api/mindmap-nodes?where[mindmap][equals]=${mindmapId}`
    )

    expect(response.ok()).toBeTruthy()
    const data = await response.json()
    expect(data.docs).toBeDefined()
    expect(data.docs.length).toBeGreaterThanOrEqual(2)
  })
})

